2014/07/24 09:43:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:43:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:43:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:43:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:43:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:44:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:45:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:46:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:47:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:48:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:49:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:50:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:51:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:52:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:53:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405140023.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405140023.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 09:54:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "upload/propertyimages/image_47_1405138619.jpg".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('upload/property...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/upload/propertyimages/image_47_1405138619.jpg
HTTP_REFERER=http://localhost/mypropertylk/list/detail/pid/47
---
2014/07/24 10:00:17 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_4` FOREIGN KEY (`district`) REFERENCES `district` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `property` (`type`, `sendemail`, `hidestreetaddress`, `dispalyprice`, `propcondition`, `pricetype`, `entrydate`, `agent`, `otheragent`, `price`, `vendorname`, `vendoremail`, `vendorphone`, `unitnum`, `number`, `streetaddress`, `areaname`, `townname`, `district`, `province`, `owner`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20).
in C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\AddPropertyAction.php (69)
in C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php (74)
in C:\xampplite\htdocs\mypropertylk\index.php (15)
2014/07/24 10:00:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_4` FOREIGN KEY (`district`) REFERENCES `district` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `property` (`type`, `sendemail`, `hidestreetaddress`, `dispalyprice`, `propcondition`, `pricetype`, `entrydate`, `agent`, `otheragent`, `price`, `vendorname`, `vendoremail`, `vendorphone`, `unitnum`, `number`, `streetaddress`, `areaname`, `townname`, `district`, `province`, `owner`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20)' in C:\xampplite\htdocs\mypropertylk\protected\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1014): CDbCommand->execute()
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(787): CActiveRecord->insert(NULL)
#2 C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\AddPropertyAction.php(69): CActiveRecord->save(false)
#3 C:\xampplite\htdocs\mypropertylk\protected\framework\web\actions\CAction.php(75): AddPropertyAction->run()
#4 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(309): CAction->runWithParams(Array)
#5 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(AddPropertyAction))
#6 C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php(74): CFilterChain->run()
#7 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CInlineFilter.php(59): PropertyController->filterAccessControl(Object(CFilterChain))
#8 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(292): CFilterChain->run()
#10 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(266): CController->runActionWithFilters(Object(AddPropertyAction), Array)
#11 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(276): CController->run('addproperty')
#12 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('property/addpro...')
#13 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/mypropertylk/property/addproperty?type=1
HTTP_REFERER=http://localhost/mypropertylk/property/addproperty?type=1
---
2014/07/24 10:01:48 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_4` FOREIGN KEY (`district`) REFERENCES `district` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `property` (`type`, `sendemail`, `hidestreetaddress`, `dispalyprice`, `propcondition`, `pricetype`, `entrydate`, `agent`, `otheragent`, `price`, `vendorname`, `vendoremail`, `vendorphone`, `unitnum`, `number`, `streetaddress`, `areaname`, `townname`, `district`, `province`, `owner`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20).
in C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\AddPropertyAction.php (69)
in C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php (74)
in C:\xampplite\htdocs\mypropertylk\index.php (15)
2014/07/24 10:01:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_4` FOREIGN KEY (`district`) REFERENCES `district` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `property` (`type`, `sendemail`, `hidestreetaddress`, `dispalyprice`, `propcondition`, `pricetype`, `entrydate`, `agent`, `otheragent`, `price`, `vendorname`, `vendoremail`, `vendorphone`, `unitnum`, `number`, `streetaddress`, `areaname`, `townname`, `district`, `province`, `owner`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20)' in C:\xampplite\htdocs\mypropertylk\protected\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1014): CDbCommand->execute()
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(787): CActiveRecord->insert(NULL)
#2 C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\AddPropertyAction.php(69): CActiveRecord->save(false)
#3 C:\xampplite\htdocs\mypropertylk\protected\framework\web\actions\CAction.php(75): AddPropertyAction->run()
#4 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(309): CAction->runWithParams(Array)
#5 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(AddPropertyAction))
#6 C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php(74): CFilterChain->run()
#7 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CInlineFilter.php(59): PropertyController->filterAccessControl(Object(CFilterChain))
#8 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(292): CFilterChain->run()
#10 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(266): CController->runActionWithFilters(Object(AddPropertyAction), Array)
#11 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(276): CController->run('addproperty')
#12 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('property/addpro...')
#13 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/mypropertylk/property/addproperty?type=1
HTTP_REFERER=http://localhost/mypropertylk/property/addproperty?type=1
---
2014/07/24 10:27:09 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_3` FOREIGN KEY (`province`) REFERENCES `province` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=47.
in C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php (64)
in C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php (74)
in C:\xampplite\htdocs\mypropertylk\index.php (15)
2014/07/24 10:27:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_3` FOREIGN KEY (`province`) REFERENCES `province` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=47' in C:\xampplite\htdocs\mypropertylk\protected\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1681): CDbCommand->execute()
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1061): CActiveRecord->updateByPk('47', Array)
#2 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(787): CActiveRecord->update(NULL)
#3 C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php(64): CActiveRecord->save(false)
#4 C:\xampplite\htdocs\mypropertylk\protected\framework\web\actions\CAction.php(75): EditPropertyAction->run()
#5 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(309): CAction->runWithParams(Array)
#6 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(EditPropertyAction))
#7 C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php(74): CFilterChain->run()
#8 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CInlineFilter.php(59): PropertyController->filterAccessControl(Object(CFilterChain))
#9 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(292): CFilterChain->run()
#11 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(266): CController->runActionWithFilters(Object(EditPropertyAction), Array)
#12 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(276): CController->run('editproperty')
#13 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('property/editpr...')
#14 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/mypropertylk/property/editproperty?pid=47
HTTP_REFERER=http://localhost/mypropertylk/property/editproperty?pid=47
---
2014/07/24 10:28:34 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_3` FOREIGN KEY (`province`) REFERENCES `province` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=47.
in C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php (64)
in C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php (74)
in C:\xampplite\htdocs\mypropertylk\index.php (15)
2014/07/24 10:28:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_3` FOREIGN KEY (`province`) REFERENCES `province` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=47' in C:\xampplite\htdocs\mypropertylk\protected\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1681): CDbCommand->execute()
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1061): CActiveRecord->updateByPk('47', Array)
#2 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(787): CActiveRecord->update(NULL)
#3 C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php(64): CActiveRecord->save(false)
#4 C:\xampplite\htdocs\mypropertylk\protected\framework\web\actions\CAction.php(75): EditPropertyAction->run()
#5 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(309): CAction->runWithParams(Array)
#6 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(EditPropertyAction))
#7 C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php(74): CFilterChain->run()
#8 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CInlineFilter.php(59): PropertyController->filterAccessControl(Object(CFilterChain))
#9 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(292): CFilterChain->run()
#11 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(266): CController->runActionWithFilters(Object(EditPropertyAction), Array)
#12 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(276): CController->run('editproperty')
#13 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('property/editpr...')
#14 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/mypropertylk/property/editproperty?pid=47
HTTP_REFERER=http://localhost/mypropertylk/property/editproperty?pid=47
---
2014/07/24 10:36:43 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_2` FOREIGN KEY (`agent`) REFERENCES `user` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=47.
in C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php (64)
in C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php (74)
in C:\xampplite\htdocs\mypropertylk\index.php (15)
2014/07/24 10:36:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_2` FOREIGN KEY (`agent`) REFERENCES `user` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=47' in C:\xampplite\htdocs\mypropertylk\protected\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1681): CDbCommand->execute()
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1061): CActiveRecord->updateByPk('47', Array)
#2 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(787): CActiveRecord->update(NULL)
#3 C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php(64): CActiveRecord->save(false)
#4 C:\xampplite\htdocs\mypropertylk\protected\framework\web\actions\CAction.php(75): EditPropertyAction->run()
#5 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(309): CAction->runWithParams(Array)
#6 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(EditPropertyAction))
#7 C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php(74): CFilterChain->run()
#8 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CInlineFilter.php(59): PropertyController->filterAccessControl(Object(CFilterChain))
#9 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(292): CFilterChain->run()
#11 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(266): CController->runActionWithFilters(Object(EditPropertyAction), Array)
#12 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(276): CController->run('editproperty')
#13 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('property/editpr...')
#14 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/mypropertylk/property/editproperty?pid=47
HTTP_REFERER=http://localhost/mypropertylk/property/editproperty?pid=47
---
2014/07/24 10:46:01 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_4` FOREIGN KEY (`district`) REFERENCES `district` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=46.
in C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php (64)
in C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php (74)
in C:\xampplite\htdocs\mypropertylk\index.php (15)
2014/07/24 10:46:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1452 Cannot add or update a child row: a foreign key constraint fails (`mypropertylk`.`property`, CONSTRAINT `property_ibfk_4` FOREIGN KEY (`district`) REFERENCES `district` (`id`) ON DELETE CASCADE). The SQL statement executed was: UPDATE `property` SET `pid`=:yp0, `propcondition`=:yp1, `owner`=:yp2, `agent`=:yp3, `otheragent`=:yp4, `weeklyrent`=:yp5, `monthlyrent`=:yp6, `securebond`=:yp7, `price`=:yp8, `dispalyprice`=:yp9, `availabledate`=:yp10, `vendorname`=:yp11, `vendoremail`=:yp12, `vendorphone`=:yp13, `sendemail`=:yp14, `unitnum`=:yp15, `lotnum`=:yp16, `number`=:yp17, `streetaddress`=:yp18, `areaname`=:yp19, `townname`=:yp20, `hidestreetaddress`=:yp21, `district`=:yp22, `province`=:yp23, `bedrooms`=:yp24, `bathrooms`=:yp25, `ensuites`=:yp26, `toilets`=:yp27, `parkgaragespaces`=:yp28, `parkcarpetspaces`=:yp29, `parkopenspaces`=:yp30, `livingarea`=:yp31, `housesize`=:yp32, `housesquares`=:yp33, `landsize`=:yp34, `landsquares`=:yp35, `floorarea`=:yp36, `floorsquares`=:yp37, `tenuretype`=:yp38, `building`=:yp39, `parkingspaces`=:yp40, `parkcomment`=:yp41, `zoning`=:yp42, `outgoings`=:yp43, `eer`=:yp44, `balcony`=:yp45, `deck`=:yp46, `oea`=:yp47, `shed`=:yp48, `remotegarage`=:yp49, `swimpool`=:yp50, `courtyard`=:yp51, `fullyfenced`=:yp52, `outsidespa`=:yp53, `securepark`=:yp54, `tenniscourt`=:yp55, `spabovroundeg`=:yp56, `alarmsys`=:yp57, `biltinwardrobes`=:yp58, `dvs`=:yp59, `gym`=:yp60, `intercom`=:yp61, `rumpusroom`=:yp62, `workshop`=:yp63, `broadbandinternet`=:yp64, `dishwasher`=:yp65, `floorboards`=:yp66, `insidespa`=:yp67, `paytv`=:yp68, `study`=:yp69, `ac`=:yp70, `heating`=:yp71, `cooling`=:yp72, `solarpower`=:yp73, `solarhotwater`=:yp74, `watertank`=:yp75, `otherfeatures`=:yp76, `headline`=:yp77, `desc`=:yp78, `vediourl`=:yp79, `onlinetour1`=:yp80, `onlinetour2`=:yp81, `entrydate`=:yp82, `status`=:yp83, `type`=:yp84, `pricetype`=:yp85 WHERE `property`.`pid`=46' in C:\xampplite\htdocs\mypropertylk\protected\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1681): CDbCommand->execute()
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(1061): CActiveRecord->updateByPk('46', Array)
#2 C:\xampplite\htdocs\mypropertylk\protected\framework\db\ar\CActiveRecord.php(787): CActiveRecord->update(NULL)
#3 C:\xampplite\htdocs\mypropertylk\protected\controllers\Property\EditPropertyAction.php(64): CActiveRecord->save(false)
#4 C:\xampplite\htdocs\mypropertylk\protected\framework\web\actions\CAction.php(75): EditPropertyAction->run()
#5 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(309): CAction->runWithParams(Array)
#6 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(EditPropertyAction))
#7 C:\xampplite\htdocs\mypropertylk\protected\controllers\PropertyController.php(74): CFilterChain->run()
#8 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CInlineFilter.php(59): PropertyController->filterAccessControl(Object(CFilterChain))
#9 C:\xampplite\htdocs\mypropertylk\protected\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(292): CFilterChain->run()
#11 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CController.php(266): CController->runActionWithFilters(Object(EditPropertyAction), Array)
#12 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(276): CController->run('editproperty')
#13 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('property/editpr...')
#14 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/mypropertylk/property/editproperty?pid=46
HTTP_REFERER=http://localhost/mypropertylk/property/editproperty?pid=46
---
2014/07/24 10:59:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mypropertylk/property/editproperty".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('mypropertylk/pr...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/mypropertylk/property/editproperty?pid=47
HTTP_REFERER=http://localhost/mypropertylk/login
---
2014/07/24 10:59:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mypropertylk/property/editproperty".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('mypropertylk/pr...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/mypropertylk/property/editproperty?pid=47
HTTP_REFERER=http://localhost/mypropertylk/login
---
2014/07/24 10:59:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mypropertylk/property/editproperty".' in C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampplite\htdocs\mypropertylk\protected\framework\web\CWebApplication.php(135): CWebApplication->runController('mypropertylk/pr...')
#1 C:\xampplite\htdocs\mypropertylk\protected\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampplite\htdocs\mypropertylk\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/mypropertylk/mypropertylk/property/editproperty?pid=47
HTTP_REFERER=http://localhost/mypropertylk/login
---
